CREATE TABLE AD_TEACHER (
    id NUMBER(8),
    first_name VARCHAR2(30),
    last_name VARCHAR2(30),
    email VARCHAR2(40),
    salary NUMBER(10),
    hire_date DATE,
    bonus NUMBER(10),
    dept_id NUMBER(6),
    PRIMARY KEY(id)
);
 
CREATE TABLE AD_TEACHER_COURSES (
    id NUMBER(6),
    name VARCHAR2(40),
    session_id NUMBER(4),
    dept_id NUMBER(6),
    building VARCHAR2(30),
    room NUMBER(6),
    timetable VARCHAR2(30),
    hours NUMBER(6),
    teacher_id NUMBER(6),
    PRIMARY KEY(id)
);

INSERT ALL
    INTO AD_TEACHER (ID,FIRST_NAME,LAST_NAME,EMAIL,SALARY,HIRE_DATE,BONUS,DEPT_ID) VALUES(800,'JILL','MILLER','JMILL@SCHOOL.EDU',50000,'07-Mar-2001', NULL, 20)
    INTO AD_TEACHER (ID,FIRST_NAME,LAST_NAME,EMAIL,SALARY,HIRE_DATE,BONUS,DEPT_ID) VALUES(810,'JAMES','BORG','JBORG@SCHOOL.EDU',30000,'01-Sep-2001', NULL, 10)
    INTO AD_TEACHER(ID,FIRST_NAME,LAST_NAME,EMAIL,SALARY,HIRE_DATE,BONUS,DEPT_ID) VALUES(820,'LYNN','BROWN','LBROWN@SCHOOL.EDU',45000,'01-Mar-2003', 0.5, 30)
    INTO AD_TEACHER(ID,FIRST_NAME,LAST_NAME,EMAIL,SALARY,HIRE_DATE,BONUS,DEPT_ID) VALUES(830,'ARTHUR','SMITH','ASMITH@SCHOOL.EDU',60000,'11-Oct-2005', 0.4, 10)
    INTO AD_TEACHER(ID,FIRST_NAME,LAST_NAME,EMAIL,SALARY,HIRE_DATE,BONUS,DEPT_ID) VALUES(840,'SALLY','JONES','SJONES@SCHOOL.EDU',50000,'21-Jun-2002', NULL, 40)

    INTO AD_TEACHER_COURSES(ID,NAME,SESSION_ID,DEPT_ID,BUILDING,ROOM,TIMETABLE,HOURS,TEACHER_ID) VALUES(195,'EUROPEAN LAW',200,20,'BUILDING D',401,'MWF 9-10', 3, 810)
    INTO AD_TEACHER_COURSES(ID,NAME,SESSION_ID,DEPT_ID,BUILDING,ROOM,TIMETABLE,HOURS,TEACHER_ID) VALUES(190,'BAKING AND FINANCIAL EUROPEAN LAW',100,20,'BUILDING A',101,'MWF 9-10', 3, 830)
    INTO AD_TEACHER_COURSES(ID,NAME,SESSION_ID,DEPT_ID,BUILDING,ROOM,TIMETABLE,HOURS,TEACHER_ID) VALUES(191,'LAW AND LITIGATION',100,20,'BUILDING B',201,'MWF 9-10', 2, 840)
    INTO AD_TEACHER_COURSES(ID,NAME,SESSION_ID,DEPT_ID,BUILDING,ROOM,TIMETABLE,HOURS,TEACHER_ID) VALUES(193,'¨ECONOMIC AND FINANCIAL CRIMINAL LAW',100,20,'BUILDING C',301,'MWF 9-10', 3, 830)
    INTO AD_TEACHER_COURSES(ID,NAME,SESSION_ID,DEPT_ID,BUILDING,ROOM,TIMETABLE,HOURS,TEACHER_ID) VALUES(194,'TAX LAW',100,20,'BUILDING A',102,'MWF 9-10', 2, 820)
    INTO AD_TEACHER_COURSES(ID,NAME,SESSION_ID,DEPT_ID,BUILDING,ROOM,TIMETABLE,HOURS,TEACHER_ID) VALUES(194,'EUROPEAN PRIVATE LAW ',200,20,'BUILDING B',204,'MWF 9-10', 5, 810)

select * from AD_TEACHER_COURSES where SESSION_ID=200;
select * from AD_TEACHER_COURSES where BUILDING='BUILDING A';
select MAX(SALARY), MIN(SALARY), AVG(SALARY), SUM(SALARY) from AD_TEACHER;
select * from AD_TEACHER_COURSES where DEPT_ID=20;
select * from AD_TEACHER where DEPT_ID=10;
select * from AD_TEACHER order by NAME;
select DEPT_ID, LAST_NAME, SALARY, case(SALARY as 'New Salary' when DEPT_ID=10 then 1.25*SALARY when DEPT_ID=20 then 1.5*SALARY when DEPT_ID=30 then 1.75*SALARY else SALARY);